baseURL = "https://louis-dupont.github.io/Blog"
languageCode = "en-us"
title = "Louis Dupont"
theme = "PaperMod"

[params]
  ShowReadingTime = true
  ShowShareButtons = true
  ShowToc = true
  comments = true

[services]
  [services.googleAnalytics]
    ID = "G-GX2HR4QZL5"


[params.utterances]
  repo = "Louis-Dupont/Blog"
  issueTerm = "pathname"
  theme = "github-light"
  label="Comment"