baseURL = "https://louis-dupont.github.io/Blog"
languageCode = "en-us"
title = "Louis Dupont"
theme = "PaperMod"

[params]
  ShowReadingTime = true
  ShowShareButtons = true
  ShowToc = true
  comments = true
  ShowTags = true
  ShowCategories = true
  mainSections = ["blog"]  # Move posts to /blog/


[services]
  [services.googleAnalytics]
    ID = "G-GX2HR4QZL5"


[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    style = "monokai"

[params.utterances]
  repo = "Louis-Dupont/Blog"
  issueTerm = "pathname"
  theme = "github-light"
  label="Comment"

[taxonomies]
  category = "categories"
  tag = "tags"


[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Articles"
    url = "/articles/"
    weight = 2

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4
