baseURL = "https://louis-dupont.github.io/Blog"
languageCode = "en-us"
title = "Louis Dupont"
theme = "PaperMod"

[params]
  ShowReadingTime = true
  ShowShareButtons = true
  ShowToc = true
  comments = true
  ShowTags = true
  ShowCategories = true
  mainSections = ["blog"]  # Move posts to /blog/

  ShowRightSidebar = true
  ShowCategoriesInSidebar = true
  ShowTagsInSidebar = true

  [params.sidebar]
    home = "right"  # or "left" depending on where you want it
    sticky = true
    includeHome = true
    includeTags = true
    includeCategories = true

[services]
  [services.googleAnalytics]
    ID = "G-GX2HR4QZL5"


[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    style = "monokai"

[params.utterances]
  repo = "Louis-Dupont/Blog"
  issueTerm = "pathname"
  theme = "github-light"
  label="Comment"

[taxonomies]
  category = "categories"
  tag = "tags"


[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Work with me"
    url = "/work-with-me/"
    weight = 2

  [[menu.main]]
    name = "Articles"
    url = "/articles/"
    weight = 3

  [[menu.main]]
    name = "About Me"
    url = "/about-me/"
    weight = 4
